name: Codex PR Review

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  codex_pr_review:
    uses: oscilar/.github/.github/workflows/codex-pr-review.yml@main
    secrets:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
